-- MySQL Script generated by MySQL Workbench
-- Fri Apr 28 09:38:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema onyva
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `onyva` ;

-- -----------------------------------------------------
-- Schema onyva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onyva` DEFAULT CHARACTER SET utf8 ;
USE `onyva` ;

-- -----------------------------------------------------
-- Table `onyva`.`Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onyva`.`Device` ;

CREATE TABLE IF NOT EXISTS `onyva`.`Device` (
  `DeviceId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Os` ENUM('Android', 'iOS', 'Windows', 'Linux', 'Other') NULL,
  `Version` INT(5) NULL,
  `Ip` VARCHAR(45) NULL,
  `Identifier` VARCHAR(100) NULL,
  `RowVersion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`DeviceId`),
  UNIQUE INDEX `Identifier_UNIQUE` (`Identifier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onyva`.`Vehicule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onyva`.`Vehicule` ;

CREATE TABLE IF NOT EXISTS `onyva`.`Vehicule` (
  `VehiculeId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Trademark` VARCHAR(50) NULL,
  `Color` VARCHAR(50) NULL,
  `Seats` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1,
  `VehiculeName` VARCHAR(50) NULL,
  `DeviceId` INT UNSIGNED NULL,
  `RowVersion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`VehiculeId`),
  INDEX `Vehicule_Device_DeviceId_idx` (`DeviceId` ASC),
  INDEX `Vehicule_VehiculeName_DeviceId_Unique` (`VehiculeName` ASC, `DeviceId` ASC),
  CONSTRAINT `Vehicule_Device_DeviceId`
    FOREIGN KEY (`DeviceId`)
    REFERENCES `onyva`.`Device` (`DeviceId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onyva`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onyva`.`Club` ;

CREATE TABLE IF NOT EXISTS `onyva`.`Club` (
  `ClubId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ClubPassword` VARCHAR(100) NOT NULL,
  `ClubName` VARCHAR(100) NOT NULL,
  `RowVersion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ClubId`),
  UNIQUE INDEX `Club_ClubId_ClubPassword_Unique` (`ClubPassword` ASC, `ClubId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onyva`.`Passenger`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onyva`.`Passenger` ;

CREATE TABLE IF NOT EXISTS `onyva`.`Passenger` (
  `PassengerId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PassengerName` VARCHAR(100) NOT NULL,
  `DeviceId` INT UNSIGNED NULL,
  `RowVersion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PassengerId`),
  INDEX `Passenger_Device_DeviceId_idx` (`DeviceId` ASC),
  UNIQUE INDEX `Passenger_PassengerName_DeviceId_Unique` (`PassengerName` ASC, `DeviceId` ASC),
  CONSTRAINT `Passenger_Device_DeviceId`
    FOREIGN KEY (`DeviceId`)
    REFERENCES `onyva`.`Device` (`DeviceId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onyva`.`Travel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onyva`.`Travel` ;

CREATE TABLE IF NOT EXISTS `onyva`.`Travel` (
  `TravelId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `DepartureTime` TIME NULL,
  `Day` ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NULL,
  `ClubId` INT UNSIGNED NOT NULL,
  `RowVersion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`TravelId`),
  INDEX `Travel_Club_ClubId_idx` (`ClubId` ASC),
  UNIQUE INDEX `Travel_Unique` (`Date` ASC, `DepartureTime` ASC, `Day` ASC, `ClubId` ASC),
  CONSTRAINT `Travel_Club_ClubId`
    FOREIGN KEY (`ClubId`)
    REFERENCES `onyva`.`Club` (`ClubId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onyva`.`Link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onyva`.`Link` ;

CREATE TABLE IF NOT EXISTS `onyva`.`Link` (
  `LinkId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TravelId` INT UNSIGNED NOT NULL,
  `VehiculeId` INT UNSIGNED NULL,
  `PassengerId` INT UNSIGNED NULL,
  `RowVersion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LinkId`),
  UNIQUE INDEX `Match_TravelId_VehiculeId_PassengerId_Unique` (`VehiculeId` ASC, `PassengerId` ASC, `TravelId` ASC),
  INDEX `Match_Travel_TravelId_idx` (`TravelId` ASC),
  INDEX `Match_Passenger_PassengerId_idx` (`PassengerId` ASC),
  INDEX `Match_Vehicule_VehiculeId_idx` (`VehiculeId` ASC),
  CONSTRAINT `Match_Travel_TravelId`
    FOREIGN KEY (`TravelId`)
    REFERENCES `onyva`.`Travel` (`TravelId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Match_Vehicule_VehiculeId`
    FOREIGN KEY (`VehiculeId`)
    REFERENCES `onyva`.`Vehicule` (`VehiculeId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `Match_Passenger_PassengerId`
    FOREIGN KEY (`PassengerId`)
    REFERENCES `onyva`.`Passenger` (`PassengerId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onyva`.`ClubIdPool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onyva`.`ClubIdPool` ;

CREATE TABLE IF NOT EXISTS `onyva`.`ClubIdPool` (
  `ClubId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ClubId`),
  UNIQUE INDEX `ClubCode_UNIQUE` (`ClubId` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
